### ISSUE TITLE
Pokemon Super Mystery Dungeon: freeze at intro (thread locking)

### ISSUE THREAD

**Issue by wwylele** [citra-emu/citra#1832]
Did some investigation, so let me explain in detail.

On real 3DS, when the game start without savegame, it goes like this:
-  Some star and flash effect
- Title screen, with camera video in the background
-  Press start
-   Game says "Finally, ..." (camera video still in the background)
-  press lower screen and hold 
-  upper screen turn to white, lower screen turn to black 
-  (camera video is no longer there) The "personality test" begins

A reference video is [here](https://www.youtube.com/watch?v=WkLRCoGV28A).

And here is what happens on citra:
- Some star and flash effect 
-  Title screen, with green background with log spamed with `Service.CAM` (because we stubbed CAM service) 
- Press start
-  Game says those welcome text (still green background and log spamming)
-  press lower screen and hold 
- upper screen turn to white, lower screen turn to black
-  freeze (still spamming `Service.CAM`)

At freezing, the wait tree shows that the main thread is waiting for another thread (thread_id = 9). That thread continues calling CAM service.

Then I did some tracing and here is the result:
before title screen, main thread creates event A, then creates thread 9 (camera thread)
The camera thread is doing the follows:
call `CAM::SetReceiving`→...→ `WaitSynchronizationN(...)` → ... → loop
The `WaitSynchronizationN(...)` is waiting for ONE OF the following 3 objects (in array order):
- "event A"
- `CAM:completion_event_cam1`
- `CAM:interrupt_error_event`

However, when the game begins to show the welcome text, the waiting strategy of the camera thread changes somehow: the order of 3 objects for `WaitSynchronizationN(...)` changes to
- `CAM:completion_event_cam1`
- `CAM:interrupt_error_event`
- "event A"

the event A is never signaled until "screen turn to white, lower screen turn to black", where the event A is signaled and the "personality test" is supposed to begin. So this event is for sure the stop signal of camera thread. The problem is: this event becomes the last one in camera threads waiting list, and [we always signal `CAM:completion_event_cam1` immediately](https://github.com/citra-emu/citra/blob/98923ab6e566f06b61d2dc671a1b8aec87f88407/src/core/hle/service/cam/cam.cpp#L84), so `WaitSynchronizationN` always catches `CAM:completion_event_cam1` but never catches "event A", which means the camera thread never knows it should stop.

I am not sure what is the correct way to fix this. Is the way implementing `WaitSynchronizationN(...)` wrong? Or we just need to give a time delay to signal camera events?

**Comment by Subv** [comment]
Maybe we should simulate the delay of the camera hardware

**Comment by JayFoxRox** [comment]
This should have been fixed by #1837?

**Comment by Dragios** [comment]
Nope, the log still spams with Service.CAM.

**Comment by wwylele** [comment]
@JayFoxRox: #1837 is not mean to fix this, it was a another bug.
@Dragios even if this is fixed, log spam will still happen before we actually implement camera service.

**Comment by wwylele** [comment]
Found another similar issue in FIFA13/15's intro - this time is Y2R's completion event. Giving the event a 1 cycle delay will bypass the freeze and play the "EA sports" cutscene. (Though the game will still freeze after the cutscene)

**Comment by AlmariJosh** [comment]
How to fix this \??? How to fix Pokemon Super Mystery Dungeon? It kept freezing after the main title ... what to do>>??? Pleasse.. I need a reply now :( I'm desperate on playing the game

**Comment by wwylele** [comment]
@AlmariJosh I already replied to you:

> This is the bug tracker for developers of Citra. 
> 
> Please Use our [Citra Forum](https://discuss.citra-emu.org/) for questions and support instead. Note that you won't get any support if you
>  - use any kinds of non-official build, or
>  - use pirated copies of the games, 3DS BIOS files or any copyrighted content.
> 
> If you really want to report an issue which is not your personal problem but bugs in Citra, please review [guidelines for contributing](https://github.com/citra-emu/citra/blob/master/CONTRIBUTING.md) carefully, and follow the instructions there.

Please stop spamming.
