### ISSUE TITLE
Mario & Luigi : Paper Jam - Crash on a fight with stack of paper gombas

### ISSUE THREAD

**Issue by Avoltance** [citra-emu/citra#2910]
Game : Mario & Luigi : Paper Jam (European version - 0004000000132800)

Last Citra version tested : HEAD-f251b88

The game work well in globaly. There is some lags in combat with paper ennemis (like explained in issue #2712), but before the first combat with stacked ennemis beggin (when the game load the battle) ( https://puu.sh/xofeV/43fc493e85.png ) in the early beggining of the game, citra crash, on every test (last frame : https://puu.sh/xofoL/dd9312d5a4.png ). There is the log : https://pastebin.com/S5jJZxMn

If i refered on the log, i think it's caused by a missing Blend Equation type in file "video_core/renderer_opengl/pica_to_gl"

**Comment by Avoltance** [comment]
These links to Github Files can be related to this bug :
* https://github.com/citra-emu/citra/blob/f251b8873a6981431bc0383ec86a6b1c986c8e2b/src/video_core/renderer_opengl/pica_to_gl.h#L95
* https://github.com/citra-emu/citra/blob/f251b8873a6981431bc0383ec86a6b1c986c8e2b/src/video_core/swrasterizer/framebuffer.cpp#L280

**Comment by jroweboy** [comment]
This sounds like a recent regression that the build you mentioned has https://github.com/citra-emu/citra/issues/2902 It should have been fixed with https://github.com/citra-emu/citra/pull/2905 Please retest with the latest nightly and close this if it works again.

**Comment by Avoltance** [comment]
@jroweboy Tested in the lasted nightly build, and same crash with the same logs. I don't think it's a recent regression, since it has existed since June ( https://community.citra-emu.org/t/mario-luigi-paper-jam-crash-on-a-fight-with-stack-of-paper-gombas/2072 ). Last Citra version tested updated.

**Comment by Subv** [comment]
From 3dbrew: `Blend equations 5, 6, 7 appear to behave the same as blend equation 0 (Add) `.

We should add those to the OpenGL wrapper

**Comment by wwylele** [comment]
Similar to issue #2276, and #2658 was the last PR that contains research for it (but didn't fix it), which is also the time when it get documented on 3dbrew. It was remained unimplemented intentionally for further research.

I propose to add these to the OpenGL wrapper and report telemetry.

Also, this might still be a regression, or a difference caused by region/language/whatever settings. IIRC I was able to go into a stacked enemies battle (although there was a huge lag). This test was around proctex test, and it was on friend's computer so I can recall it exactly, but I think it was a EUR game with language set to english.

**Comment by Avoltance** [comment]
@wwylele There is a savefile near the crash : https://github.com/citra-emu/citra-games-wiki/raw/master/games/mario-luigi-paper-jam/savefiles/PaperJam-NearCrash-EUR.zip

**Comment by wwylele** [comment]
This is interesting.
I tested on the same version f251b88, using the same game from the same region, with language set to French (as I guessed from the screenshot), and using the save above, but __can't reproduce__ the crash.

Also, there is another thing to note in the log:
```[  28.495703] HW.GPU <Critical> video_core\shader\shader_jit_x64_compiler.cpp:Pica::Shader::JitShader::Compile_NextInstr:811: Unhandled instruction: 0x20 (0x80000000)```
Don't confuse this with GS's 0x2a and 0x2b) - instruction 0x20 is just invalid. Also, I didn't get this log on my side.

So either it is a broken ROM, or something went horribly wrong.

**Comment by Avoltance** [comment]
`[ 28.495703] HW.GPU <Critical> video_core\shader\shader_jit_x64_compiler.cpp:Pica::Shader::JitShader::Compile_NextInstr:811: Unhandled instruction: 0x20 (0x80000000)` is linked to lags when you battle versus paper ennemis. And i dump twice my game for try, but nothing change. Can be relative to the system ?

**Comment by wwylele** [comment]
I do get lags when battling versus paper enemies, but I don't get the log at the time.

I will try to get a clean dump when I get time. Anyone else with a clean dump can confirm this bug?

**Comment by 1425720626** [comment]
I didn't have this crash. Still lags though.

**Comment by Truhard** [comment]
This bug still exists, confirmed with a clean dump. I tested it on HEAD-5620327, latest version at the time. I also lag when fighting paper models.

**Comment by Avoltance** [comment]
Tested in HEAD-f47bf6c, and there is no bug ! Still lags, like the game play at 12% but, it's work !

**Comment by Dragios** [comment]
If possible could you bisect to which nightly version that fixes this?

**Comment by TheKoopaKingdom** [comment]
Acoording to [this](https://community.citra-emu.org/t/m-l-paper-jam-crash-with-paper-goombas-again/4294/17?u=thekoopakingdom) and [this](https://community.citra-emu.org/t/mario-luigi-paper-jam-bros-crash/5290) topic on the forums, this issue still occurs. Due to the current logging system the log is terminated, but [this](https://pastebin.com/raw/zJjm721p) is all of the log collected before the crash.
