### ISSUE TITLE
Poochy & Yoshi's Woolly World - Incorrect Shadows

### ISSUE THREAD

**Issue by Krusher97** [citra-emu/citra#3321]
https://imgur.com/a/YC7aX
Hardware pictures from here : https://www.youtube.com/watch?v=TykoGWNpLfE

The shadows are improperly rendered and off centered from the objects they are supposed to belong to.

Log : [Log.txt](https://github.com/citra-emu/citra/files/1579250/Log.txt)

Game requires system fonts.

**Comment by Hexagon12** [comment]
That's not a full log. Please upload the full log with instructions listed in here: [https://community.citra-emu.org/t/how-to-upload-the-log-file/296](url)

**Comment by Krusher97** [comment]
Thats strange
Is this log full? 
[log.txt](https://github.com/citra-emu/citra/files/1579422/log.txt)

**Comment by wwylele** [comment]
`[  31.082296] HW.GPU <Critical> video_core/renderer_opengl/gl_shader_gen.cpp:SampleTexture:206: Unhandled texture type 2`
This is the unimplemented shadow map.

**Comment by mvisser81** [comment]
This shadow issue becomes a problem in level 4-6 Spooky Scraps! Don't Get Spooked! Still a problem and impossible to going further in the game. I use the latest version of Citra.

**Comment by wwylele** [comment]
There are actually two kinds of shadow in this game. One is the real-shape shadow, seen in the world map, which is confirmed rendered by shadow mapping and fixed in swrasterizer in #3516. The other is plain cirlce-shape shadow, seen ingame and in cut scene, whose rendering method is still unknown.

**Comment by mvisser81** [comment]
wwylele, SwRasterizer: Implement shadow mapping #3516 don't fixes the shadow problem in level 4-6 Spooky Scraps! Don't Get Spooked! from the game Poochy & Yoshi's Woolly World.

**Comment by Krusher97** [comment]
Maybe make a new issue for it with a log?

**Comment by FearlessTobi** [comment]
He said himself it doesn't fix the issue if I understood him correctly -> "The other is plain cirlce-shape shadow, seen ingame and in cut scene, whose rendering method is still unknown."

**Comment by wwylele** [comment]
Could you please the hardware renderer with canary or #3729 ?

**Comment by benderscruffy** [comment]
shadows in the opening cutscene are still missing.

**Comment by SleepingSnakezzz** [comment]
@Krusher97 Please retest on the latest Citra Nightly build.

**Comment by benderscruffy** [comment]
ok the shadows appear now
![Screenshot 2023-09-14 163013](https://github.com/citra-emu/citra/assets/2696404/f67f7aa3-68ae-4185-911c-f3f752db515a)
![Screenshot 2023-09-14 163100](https://github.com/citra-emu/citra/assets/2696404/f9b47db4-7443-4c20-b013-ccfb39044da6)

**Comment by SleepingSnakezzz** [comment]
@benderscruffy You're using Vulkan. Make sure to test with OpenGL, and OpenGL without Hardware Shaders enabled (so relying on Shader JIT). Lots of these old issues were before Hardware Shaders or Vulkan were implemented, after all.

**Comment by benderscruffy** [comment]
shadows appear now with OpenGL, and OpenGL without Hardware Shaders enabled
