### ISSUE TITLE
Tomadachi life - voices cutting out

### ISSUE THREAD

**Issue by ghost** [citra-emu/citra#4281]
In the game tomadachi life the voices cut out
im using Citra nightly #1009
here is footage of it happening 
https://streamable.com/y8adv

and the dialog boxes go too fast too

**Comment by Nikita11790** [comment]
still happens
#1020

**Comment by death1223** [comment]
still happens #1030

**Comment by Dragios** [comment]
Stop linking the pull request number please. You guys just referencing unrelated issue and causes unnecessary log generated.
If you still want to reference, please edit the hyperlinks manually.
[#1030](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1030)

**Comment by death1223** [comment]
Voice still cut out [#1040](https://github.com/citra-emu/citra-nightly/releases/tag/nightly-1040)

**Comment by jroweboy** [comment]
@death1223 DO NOT report builds that don't fix it. DO report when a build fixes it. If you continue to report builds that DO NOT fix it, i'll lock the conversation.

No one has even looked into the issue, and its not magically going to fix itself, so reporting every few days that its not working is pointless spam (that shows up in my inbox). Thanks for understanding

**Comment by death1223** [comment]
So no one has looked into an issue that's been open for 8 days? What's the point of this board then?

**Comment by RocketRobz** [comment]
@death1223 The issue tracker is for reporting bugs that are in (in this case) Citra.
There are many issues open, even I have one that's been open for a while (as of this post).
The point of this board is to fix those open issues, no matter how long they're open, and whenever the devs are ready.

**Comment by Superman321** [comment]
Try updating to the newest Version, then go to Emulation > Configure > System > Audio Then set Emulation to LLE
![pic](https://user-images.githubusercontent.com/43991473/49683512-954b2a80-fac6-11e8-97b9-d63c64a4420e.PNG)

**Comment by RocketRobz** [comment]
@Superman321 Still happens using LLE.

**Comment by Superman321** [comment]
Its not skipping for me anymore

**Comment by Nikita11790** [comment]
How do I open the settings (Mac)

**Comment by Superman321** [comment]
I dont know

**Comment by EmpressLexi** [comment]
Using HLE, it would appear that the voice skip happens at the exact same amount of time after an islander starts speaking, no matter the speed of their speaking, if they finish what they're saying before the amount of time, they can say full sentences.

The only situations in which they DON'T cut out, is when their speech is being timed to something, such as the rap battles or the songs you can make. I think the issue may be to do with this timing problem.
Perhaps the emulator isn't sure what to do when there is no specified time for the audio to stop playing, as Tomodachi life's sounds for voices are very variable.

Sorry if this isn't helpful, I've just been trying to figure this out for a week or two.

**Comment by FearlessTobi** [comment]
Thanks for looking into this! ^^
However I believe this bug can and will only be fixed by enabling Audio LLE in the settings which currently is a pretty heavy hit on performance. The game probably uses a audio firmware different from the standard one we emulate in HLE and this probably causes all the voice skips to happen.

**Comment by FearlessTobi** [comment]
Taken from Discord.
`
B3N30 heute um 19:41 Uhr:
@fearlessTobi the cutted audio as well as the other audio desync issues are probably fixable in HLE. ATM signaling the game that the decoder is finished isn't handled properly but instead we just signal in a fixed interval. But signaling when the decoder is done is probably not enough but we have to do a similar aproach like with the file open/close/read delay. Nevertheless I think it is fixable. But thats just a theory and I didn't verify anything.`

**Comment by Panquesito7** [comment]
Each time an islander calls from the cell phone about problems related to the baby, the voices don't cut that much: they last longer than they normally do.

**Comment by DogeIsCut** [comment]
this is still happening, any fix without lle? becuase it lags waaaay to much for me when i use it

**Comment by HEYimHeroic** [comment]
yeah, if there's a possible HLE fix with this, i'd love to see it happen; text that automatically scrolls (which 99% of spoken text is) goes really fast and in some cases is unreadable.

**Comment by jroweboy** [comment]
I started investigating this issue without any results yet. I've got a few more ideas on what to test, but i'm still not sure whats wrong. It would help a lot if someone could upload a save file here that is close to a spot that can replicate the issue and tell me how to replicate it as well. Currently I have to fill in the a bunch of set up stuff like player name everytime i want to test a change and click through a bunch of menus. Would really appreciate it if there was a faster test case <3 thanks!

**Comment by HEYimHeroic** [comment]
[savedataArc.txt](https://github.com/citra-emu/citra/files/3919430/savedataArc.txt)
here you go!! hope this helps; just open any Mii's apartment and tap the three ... icon, and they'll usually say something. if it's too short, try again.

**Comment by vvanelslande** [comment]
game says it's corrupted

**Comment by HEYimHeroic** [comment]
the save data? it works just fine for me...

**Comment by SmiVan** [comment]
With Tomodachi Life a good way to test would be to listen to Mii News, as the voices always cut out with the relatively long phrases that Mii News uses.

Making a character with a very slow speaking speed would help detect this as well.

**Comment by kabuk1h3r3** [comment]
hi here, i made a save file (JPN) after making a mii with the slowest voice setting possible and interacted with them in their apartment, one of which was tapping their speech bubble.

---

[savedataArc.txt](https://github.com/citra-emu/citra/files/3954304/savedataArc.txt)

**Comment by JambyJC** [comment]
Okay, so I don't know if this will help anyone, but this happened to me for the longest time and I couldn't figure out why. When I was playing I realized I was playing on Nightly instead of the normal Citra. I loaded the game up on normal Citra and the voices stopped cutting out. Yes, I know, I'm dumb. That is the fix to the problem, at least for me.

**Comment by wwylele** [comment]
@JambyJC But Nightly *is* the normal citra. Which version were you actually using?

**Comment by JambyJC** [comment]
@wwylele Sorry for any confusion. I meant the Canary version of Citra.

**Comment by wwylele** [comment]
@JambyJC so you mean, there is voice cutting out issue on nightly, but it works fine on canary?

**Comment by JambyJC** [comment]
@wwylele Exactly.

**Comment by kabuk1h3r3** [comment]
it's weird because i have canary and i still have issues with the audio...

**Comment by JambyJC** [comment]
Have you tried disabling audio stretching?

**Comment by kabuk1h3r3** [comment]
disabled audio stretching and the mii's voices still cut off, unfortunately. every suggestion that's been made in the past to fix the audio i've tried with little to no results.

**Comment by SmiVan** [comment]
Checked on Canary 1511 and the audio cut-off is still present (with and without audio stretching).
Very odd, @JambyJC are you certain the voices stopped cutting off? 
Which exact version are you on?

Also, just for your information, there are some conditions in which the voices don't cut off, e.g. in songs. 
Be sure to check Mii News and long phrases in rooms.

**Comment by JambyJC** [comment]
I don't know if this gives the information on what version I'm on, if this isn't enough information then tell me what I need to do instead.
![Screenshot_129](https://user-images.githubusercontent.com/58903017/70874193-e73e5000-1f65-11ea-81cf-c59ae9200429.png)

**Comment by JambyJC** [comment]
And yes, I am sure that the voices stopped cutting out once I switched to Canary. The news works fine.

**Comment by PKPeri** [comment]
Any updates on this yet? I'm on Canary and it still seems to cut off, LLE makes my game lag.

**Comment by jroweboy** [comment]
@PKPeri I've started investigating the issue, but I have no fix for it yet. Since its near Christmas, I've been really busy with other things and can't promise I'll be able to find a fix for it any time soon. I'll post back here when theres anything new to report.

**Comment by PKPeri** [comment]
@jroweboy Alright, that's fine

**Comment by HEYimHeroic** [comment]
yeah @PKPeri usually they'll try to get it to work on HLE and not *just* on LLE, if that makes sense ^^

**Comment by Aggekis** [comment]
Check this out. How is this youtuber not having a problem with the audio if he is using an emulator? maybe is another one but still useful... min 3.36. https://www.youtube.com/watch?v=FYeVKq8kxFg

**Comment by BreadFish64** [comment]
@Aggekis they are probably using an unofficial build with a hack.

**Comment by Josh138** [comment]
Yes, @Aggekis. I have seen that YouTuber play the game using an emulator on his computer. I am still puzzled how he could freely play without the speech cuts.

**Comment by JambyJC** [comment]
I can play freely without the speech cuts as well. I guess its just getting lucky

**Comment by BreadFish64** [comment]
@JambyJC how recently did you play it, we put a PR into Canary last night that should fix some audio bugs, but I don't think this is one of them.

**Comment by Josh138** [comment]
@JambyJC Which ROM did you download? Could you link the site?

**Comment by Superman321** [comment]
@Josh138 You do realize it's Piracy & illegal to download/share roms?

**Comment by TepperPepper** [comment]
Running Canary 1589 and using LLE the voices don't cut short, but the game lags (runs at around 6 FPS). With HLE the voices still cut.

**Comment by SmiVan** [comment]
> @JambyJC how recently did you play it, we put a PR into Canary last night that should fix some audio bugs, but I don't think this is one of them.

Checked on master-1435aab3 (2020-03-13) and the issue is still present, so unfortunately that PR didn't fix this.

**Comment by SmiVan** [comment]
Well if JambyJC is not having this issue, perhaps it is platform dependent?
I'm running Citra on Ubuntu LTS 18.04.4, and I used to run it on macOS last year and the issue was present on both of those.
Could someone else with a Windows OS (which I presume is what JambyJC using) check whether or not it is absent specifically on that.

**Comment by SmiVan** [comment]
I've done a `git bisect` through the last 2 years of citra commits, and arrived at the first commit where Tomodachi Life is supported (5dacf92fd73a9abe721a6525dda633d7b0c6133c), and never seen any versions which have sound working. 

Next I'm going to check out the exact commit that JambyJC uses - a8f5c57.

**Comment by vvanelslande** [comment]
@SmiVan that weird commit is from a deleted unofficial branch and the issue is fixed with custom ticks.

**Comment by SmiVan** [comment]
I've tried setting various lower and higher CPU clock speed values on the recent commit that @jroweboy put out (which supposedly is the same as "custom ticks"), but to no avail. 
Is there some particular value that it should be set to, or is this just an unrelated patch that uses the same terminology by accident?

**Comment by pmalleytally** [comment]
was having the same voice cut-out issue on nightly. saw that some people had luck after switching to qt, so i tried that. weirdly enough, it fixed my issue.

**Comment by SmiVan** [comment]
@pmalleytally What do you mean by "switching to qt"? Were you using the retroarch edition before or something?

**Comment by pmalleytally** [comment]
@SmiVan i was originally using your regular citra nightly. i heard some good things about "citra-qt.exe". it was easy to find, i just typed in citra and it popped up along with canary and nightly, since i have both.. i opened qt, and ran the tomodachi life rom on it. it worked like a charm, though very, very long sentences do sometimes still get cut out. you can see qt in the screenshot i attached.
![Screenshot_1](https://user-images.githubusercontent.com/66220483/83431956-c4adcf80-a3fd-11ea-9e2d-d9ff5fc46e62.png)

**Comment by Gamegenorator** [comment]
Something I noticed that might help to figure out what's causing the issue, the audio cutting out does not exist on Citra for Android, it appears to act perfectly fine no matter my settings.

**Comment by xperia64** [comment]
Fixed in #5548
