### ISSUE TITLE
Slime Mori Mori 3: Multiplayer host name blinks in and out, breaks completely on join

### ISSUE THREAD

**Issue by CakeLancelot** [citra-emu/citra#4867]
## Description
In Slime Mori Mori 3, the multiplayer feature of Citra only functions partially: the game's hosting function will appear to work without issue, but when trying to join in another instance of Citra the name of the host blinks in and out intermittently. See screenshot/video section for more detail.

If you try to join the room when the name is blinking, the host will see a blank player name join. If you try ready up on the host side the state of the connected player will not change. If you cancel the connection on the joining side, both players will return to the lobby and the host will get a 'connection interrupted' message.

According to a [previous comment](https://github.com/citra-emu/citra/pull/4690#issuecomment-472341562) made by @B3n30 : 
> The part that introduced the "flickering" was https://github.com/citra-emu/citra/blob/master/src/core/hle/service/nwm/nwm_uds.cpp#L133-L141 . This part was necessary since otherwise a client would show all received beacons as a different host. Most games handled this fine after we added that part but in some games it introduced a flickering. We never fully checked on hardware how the beacons are erased from the buffer, though. We tried to look at the disassembly but didn't came to a conclusion. So a small homebrew might give a better understanding of that part.

So this issue may affect other games as well: I do not know which games however.

## To reproduce:
1. Create 2 Citra folders on the same machine with a seperate 'user' folder in each one (portable install). Also ensure that you regenerate the console ID for one of the instances.
2. Start the game on both instances with a save file that's far enough in to access the multiplayer feature.
3. Set up a unlisted room on one instance and direct connect with the other.
4. Host a multiplayer room in one instance of the game.
5. Go to join in the other game instance, and see the game name blinking.
6. (optional) Try to join room by spamming the A button, get various weirdness and disconnection message.

## Screenshots/Video
Aforementioned blinking (framerate is fairly low in this GIF, check video below for better quality):
![2019-08-02_19-12-58](https://user-images.githubusercontent.com/5341136/62404403-9d763f80-b559-11e9-91c2-92dfb3a5220d.gif)
Folder setup for each player:
![image](https://user-images.githubusercontent.com/5341136/62404328-dfeb4c80-b558-11e9-83e9-ca94264c258c.png)
Both players have unique console ID:
![image](https://user-images.githubusercontent.com/5341136/62404368-4ec8a580-b559-11e9-9e71-2d754a443c97.png)
Video of me recreating the bug:
https://www.youtube.com/watch?v=LqUHr1IBPBo

## Specifications
Citra Nightly 1319 (both instances)
CPU: AMD Ryzen 1600
GPU: AMD RX5700

## Log Files
[Player 1 citra_log.txt](https://github.com/citra-emu/citra/files/3463191/citra_log.txt)
[Player 2 citra_log.txt](https://github.com/citra-emu/citra/files/3463192/citra_log.txt)

If you need any additional information in order to troubleshoot, please let me know.

**Comment by FearlessTobi** [comment]
A similar issue exists in one of the Mario Party games for 3ds. (IIRC MP the Top 100?)

**Comment by MojoJojoDojo** [comment]
I saw that there are some PRs that change how UDS/multiplayer works so maybe its fixed now? (i need to retest some things too).
Warioware gold got improved by it.

**Comment by CakeLancelot** [comment]
It seems that the status of this game has improved slightly! The host name still blinks in/out - but if you spam the A button to join when the name is onscreen, the game information will now sync up. So the player name, which team they're on, which gamemode and time setting is selected, etc. 

However, once you're in the game lobby performance will drop severely. From a locked 30FPS to 6-10FPS on both the instance client and host instance. Upon exiting the lobby and attempting to get in-game, the client instance crashes and the host game hangs and eventually gives a connection error screen.

**Potentially relevant log snippets:**
```[  86.518092] HW.Memory <Error> core/memory.cpp:Write:357: unmapped Write16 0x00000000 @ 0x0000000C at PC 0x00243F70
[  86.518093] HW.Memory <Error> core/memory.cpp:Write:357: unmapped Write8 0x00000000 @ 0x0000000E at PC 0x00243F70
[  86.518094] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000000 at PC 0x00243F70
[  86.518095] HW.Memory <Error> core/memory.cpp:Read:322: unmapped Read32 @ 0x00000000 at PC 0x00243F70
```
^ Once the first player joins, these messages occur rapidly on the host instance
```
[  83.441959] Debug <Critical> core/hle/service/nwm/nwm_uds.cpp:operator():1100: Assertion Failed!
```
^ Last line from the client instance before it crashed

**Full logs (Debug logging):**
[citra_log_host.zip](https://github.com/citra-emu/citra/files/5358596/citra_log_host.zip)
[citra_log_client.zip](https://github.com/citra-emu/citra/files/5358598/citra_log_client.zip)

**Video of the error/crash:**
https://youtu.be/Sbyq2qLPm3c

**Comment by MojoJojoDojo** [comment]
Codename S.T.E.A.M got the same issue.

**Comment by no12321** [comment]
Is this error still present on the latest builds of Canary? @CakeLancelot

**Comment by CakeLancelot** [comment]
> Is this error still present on the latest builds of Canary? @CakeLancelot

Just checked, and yes the issue is still present:

https://user-images.githubusercontent.com/5341136/113464340-6b357900-93f1-11eb-9754-bbc5f02ef298.mp4
