### ISSUE TITLE
Issues with new texture dump/replacement implementation

### ISSUE THREAD

**Issue by Nintynuts** [citra-emu/citra#6486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Nightly 1890-1894

### Description of Issue

I've been working on a texture pack for Luigi's Mansion, and when I updated the other day I realised all the files being dumped now had different hashes and a `_mip#` suffix. I looked here and found that #6452 had been merged with lots of great-sounding changes. I set about re-dumping all my textures so I could find name equivalents and rename all my old texture replacements to the new format and hashes before continuing with my texture pack. I also noticed that the stuttering from loading and dumping textures is much better now it's asynchronous.

However, as I started playing and using it, I have noticed a few issues:
- Old screen buffers re-appearing when the screen should be black - this seems to happen in particular when returning to the lab after beating king boo, and the bottom (and sometimes also top) screens show a frame from earlier in the game when the screen should be black. I could make a video to demonstrate this if it's necessary.
- Not all textures are being dumped - For the vast majority they are, but 3 in particular which won't dump are the Gameboy Horror map screen sprites for the stairs (going up), foyer stairs and the 8-bit Luigi sprite. I already had replacements for these, but haven't been able to match them up with new hashes because the files are missing. I wonder if this is due to a hash collision since it wouldn't overwrite an already dumped file? I hope not as this would require changing the hashes again, and I'd have to re-dump everything. #5553 would be helpful if that was the case.
- Files are dumped in a different order - This is minor, but previously when files were dumped the mipmaps would always be in the same size order, so I could use the timestamps to work out which were mipmaps. This isn't necessary now because the files indicate which mipmap they are, but it would still be preferable for them to always appear in size order when sorted by date. It would also be great if I could disable dumping mipmaps 1+ since I only care about replacing the highest resolution one.

Examples of dumped files, both sorted by date order
Before:
![image](https://user-images.githubusercontent.com/11946792/235332106-a4e8d244-e7b4-4323-b493-773d5a36e522.png)
After:
![image](https://user-images.githubusercontent.com/11946792/235332058-f435959d-22de-411d-a612-d85e7926cbf4.png)

Finally, there was mention in the changes that there's some new material system which allows for adding normal maps when they weren't previously used by the game, which I would love to try, but can't see any explanation of how to use.

### Expected Behavior

- Screens should not show old frames instead of black
- All textures should be dumped
- File timestamps should be consistently sequential with mipmap size (and not interrupted by other textures)

### Reproduction Steps

The old frame issue is hardest to reproduce because it happened right at the end of the game, although I have a feeling it happened somewhere else and I just can't remember - maybe at the end of each area. I'm sure before it just had a black screen in the same situation.

The dumping issues can be reproduced by running the game with the dump option enabled and just getting to the foyer.

### Log File

I don't think this is helpful in this situation, but here you go: [citra_log.txt](https://github.com/citra-emu/citra/files/11360454/citra_log.txt)

### System Configuration

CPU: i7-3770K
GPU/Driver: GTX 2070/452.06*
RAM: 8GB
OS: Windows 10

* old driver to support 3D Vision, but they haven't changed since I last used citra, and it's not causing these issues

**Comment by GPUCode** [comment]
The gist of it, is that there are now two hash formats the old and new one. The old hash format is the one used by all existing texture packs and to retain compatibility is supported by the loader. The dumper now dumps exclusively in the new format so that's why the hash is different. By creating a new dump you can use it to convert your existing pack to the new format automatically with this script: https://github.com/GPUCode/citra-pack-convert

The dumping order is different because dumping is asynchronous, there isn't much that can be done about it, other than having a toggle to make it synchronous.

I'm interested in the first issue, could you make a video about it

**Comment by Nintynuts** [comment]
> The gist of it, is that there are now two hash formats the old and new one. The old hash format is the one used by all existing texture packs and to retain compatibility is supported by the loader. The dumper now dumps exclusively in the new format so that's why the hash is different. By creating a new dump you can use it to convert your existing pack to the new format automatically with this script: https://github.com/GPUCode/citra-pack-convert

Yeah, I understood all that already. That script would have been handy, but I've effectively did the same with other tools. 

> The dumping order is different because dumping is asynchronous, there isn't much that can be done about it, other than having a toggle to make it synchronous. 

I know it's because it's asynchronous, I just wondered if the textures could be queued on a separate thread or batched rather than (presumably) every texture being done on a separate thread. 

> Disabling mipmap is possible but because the hash for them is different you would need to enable the skip_mipmap option in the pack.json file, which locks you out of dds packs

I was wondering if since you can detect that they're mipmaps at runtime, you could either:
- use the texture 0 hash for all mipmap dumps and use the mip# to tell them apart
- down-sample the custom texture when creating mipmaps, either automatically or by putting a lookup in the json file (generated when dumping). 
I don't really know what you mean by dds packs, so I'm not sure what the impact of it is. 

> I'm interested in the first issue, could you make a video about it

I'll try to, sure.

> To use normal maps the game must make use of fragment lighting which I'm pretty sure luigi's mansion does. All normals are named after their respective textures just with a .norm prefix added before the file extension. So filename.png is filename.norm.png.

Cool, I will give it a go.

**Comment by Nintynuts** [comment]
Having fixed the textures with the wrong name, I was checking the map and noticed that it was blurry and texture filtering had been turned off (I use 4x internal and BRZ). So I turned it back on and everything looked awful (worked mostly fine before with it on). Here are examples (filtering disabled on left, enabled on right):

![Luigi's Mansion Filtering issue 50%](https://user-images.githubusercontent.com/11946792/235353866-334b04de-0647-44f0-997d-d79f4a2df964.png)

**Comment by GPUCode** [comment]
> I know it's because it's asynchronous, I just wondered if the textures could be queued on a separate thread or batched rather than (presumably) every texture being done on a separate thread.
> 

Batching is not impossible but a bit hard with the current rasterizer cache design. Reducing the number of worker threads to one, is possible and I can add an option if you want, keep in mind though that the same thread pool is also used for async decoding so it will slow that down a tiny bit too.

> I was wondering if since you can detect that they're mipmaps at runtime, you could either:
>     use the texture 0 hash for all mipmap dumps and use the mip# to tell them apart
>     down-sample the custom texture when creating mipmaps, either automatically or by putting a lookup in the json file (generated when dumping).
> 
> 
> I don't really know what you mean by dds packs, so I'm not sure what the impact of it is.

I personally don't see how the first option is any useful, you end up with the same amount of dumps but the mips have incorrect hashes which means you will eventually need to redump them. The second option can be implemented with the skip_mipmap option. When that is enabled, citra will only upload the base level and automatically generate mipmaps from it.

dds packs refer to using compressed formats like BC7/BC5 and ASTC which reduce texture sizes and reduce the loading time.

> EDIT: I thought I'd try dumping with a clean slate and the missing textures were dumped correctly this time, however when I looked for the texture in my backup I found a texture with the same name but a different content. It's possible that this is a mistake from when I was trying to map the new names to the old names, but I'm not sure.

Alright glad to hear that. I still recommend that script so you can both save time and ensure it's correct, but that's your call.

Regarding the glitches you reported, I was made aware of them yesterday and were a regression from another recent PR. They have been fixed in this PR https://github.com/citra-emu/citra/pull/6479 so it would be nice if you could give it a shot

**Comment by Nintynuts** [comment]
> Batching is not impossible but a bit hard with the current rasterizer cache design. Reducing the number of worker threads to one, is possible and I can add an option if you want, keep in mind though that the same thread pool is also used for async decoding so it will slow that down a tiny bit too.

Having the option to use only one thread to ensure the same order as before would be nice, but maybe isn't necessary if an option could be added to skip dumping mipmaps entirely, since the order will no longer matter. Being able to load and save on different background threads might be useful though (if it's a pool of more than 1 then I guess it will, so maybe it's fine as it is).

> I personally don't see how the first option is any useful, you end up with the same amount of dumps but the mips have incorrect hashes which means you will eventually need to redump them. The second option can be implemented with the skip_mipmap option. When that is enabled, citra will only upload the base level and automatically generate mipmaps from it.

I wasn't sure if there was a circumstance where modders might want to make a mipmap different to its lv0, if not and the skip_mipmap option does that, then mipmaps are effectively useless anyway (so don't need dumping in the first place).

If they are needed, I thought hashing only lv0 and using it with the mipN suffix for all mipmaps would be a simpler alternative that leaves a connection between the file names, but I just realised because the size is first it wouldn't sort in windows, you would have to put the dimensions last. I also realise now that mipN would be a little redundant if you kept the dimensions in the name and used the same hash (at least for the purpose of retrieving the texture in code).

> dds packs refer to using compressed formats like BC7/BC5 and ASTC which reduce texture sizes and reduce the loading time. Because they are compressed the vast majority of GPUs don't support blit operations on these, only copying, meaning citra can't rescale them.

Ah, ok. I'm not that bothered about texture loading times now it's done asynchronously, so that's not an issue. 

> Alright glad to hear that. I still recommend that script so you can both save time and ensure it's correct, but that's your call.

Too late for the script I'm afraid. I think I've found all the erroneous files now though. The system I found is nice and straight forward, but I didn't think of it right away, so something must have got messed up prior to that.

> Regarding the glitches you reported, I was made aware of them yesterday and were a regression from another recent PR. They have been fixed in this PR #6479 so it would be nice if you could give it a shot

Glad to hear that's already fixed, I have nightly, I guess I'd need canary to see that one?

**Comment by Nintynuts** [comment]
Here's a video of the issue I mentioned, this is with custom textures disabled:
https://user-images.githubusercontent.com/11946792/235518940-e2c11801-2975-444c-9301-9b64237cc1f2.mp4

Also, here's a video from youtube of how it used to and should look (black screen):
https://youtu.be/ZopB0Msre5E?t=668

**Comment by Nintynuts** [comment]
@GPUCode I also tried adding normal maps, but as far as I could tell they weren't being used, so I guess it isn't compatible? Is it only normal maps which can be added?

**Comment by GPUCode** [comment]
Can you post a log file when you try to use the normal map? Also mind describing how you enabled/try to use it?
The flicker issues should be fixed in latest canary, you should try that

**Comment by Nintynuts** [comment]
> Can you post a log file when you try to use the normal map? Also mind describing how you enabled/try to use it? The flicker issues should be fixed in latest canary, you should try that

Here are the last two log files:
[citra_log.txt](https://github.com/citra-emu/citra/files/11408521/citra_log.txt)
[citra_log.txt.old.txt](https://github.com/citra-emu/citra/files/11408522/citra_log.txt.old.txt)

The files are named the same as the corresponding diffuse texture with `.norm` added before `.png` like so:
![tex1_128x128_96847077F447977C_12_mip0 norm](https://user-images.githubusercontent.com/11946792/236521423-89192388-e01c-454f-8c88-6910f48e77fb.png)
![tex1_128x128_96847077F447977C_12_mip0](https://user-images.githubusercontent.com/11946792/236521427-e17d67e7-9860-4d67-bd55-eeaa6344fdb5.png)

I will give Canary a try next.

**Comment by Nintynuts** [comment]
@GPUCode The Canary build does seem to have fixed the texture filtering issue 👍

Not noticed the normal maps having any effect though.

**Comment by GPUCode** [comment]
Can you try mapping the hash in the pack.json file? Rename the textures to something else and add this
"textures" : {
     "96847077F447977C" : [
          "texture.png",
          "texture.norm.png"
     ]
}

**Comment by Nintynuts** [comment]
Tried it, but still doesn't seem to be having any effect. I've been switching back and forth between custom and original textures with F7 and the only difference is the higher resolution. I've also been trying it in unlit rooms with the torch as that seems more likely to use runtime lighting which could be affected by normals, but it doesn't seem to make a difference.

**Comment by GPUCode** [comment]
Ok can you show me the area so I can check this out in renderdoc? Is it reachable with the save file you have provided?

**Comment by Nintynuts** [comment]
That particular door is used in B1 and 3F, which you can access in area 2 and onwards, and should be accessible in the save I gave you. The 3F doors will be unlit from the corridor side, and lit within the rooms (but I suspect this is mostly vertex lighting).
