### ISSUE TITLE
Harvest Moon The Lost Valley hangs at title screen

### ISSUE THREAD

**Issue by JohnGodgames** [citra-emu/citra#961]
![hmtlv](https://cloud.githubusercontent.com/assets/11453507/8792581/6eb22472-2f69-11e5-8b97-0425f00b43cb.PNG)

SHORTENED LOG: http://pastie.org/10303511

**Comment by Zaneo** [comment]
Speaking with @Subv on IRC he mentioned this might be related to DLC. As am:app deals with that, and a similar issue has been seen in Steel Diver. Below you can see the menu as it should be rendered, with the DLC option.
![dlc](https://cloud.githubusercontent.com/assets/295949/8793353/7a82e398-2f43-11e5-9f6e-63cb291b0131.png)

**Comment by JohnGodgames** [comment]
#962 Not working for me.Before menu it should be a Touch the touch screen

reference: https://www.youtube.com/watch?v=Yvr4fpvR0Ho

**Comment by JohnGodgames** [comment]
Fixed with some recent updates (checking dlc content)

**Comment by amirlou** [comment]
its got Fixed with new master but got buggy texture with jit enable and after i sleep for first time in game i get black screen

![xx2 2016-05-01 01-26-27-41](https://cloud.githubusercontent.com/assets/16171668/14938547/5f5b4964-0f3c-11e6-874d-8e20305fd8e5.jpg)
![xx2 2016-05-01 01-27-25-71](https://cloud.githubusercontent.com/assets/16171668/14938548/5f657bdc-0f3c-11e6-9133-c209386a355d.jpg)
![xx2 2016-05-01 01-27-35-33](https://cloud.githubusercontent.com/assets/16171668/14938549/5f6c0a24-0f3c-11e6-845c-20ea8d6387b7.jpg)

**Comment by JayFoxRox** [comment]
@amirlou: If this is fixed we should close it, if this game hangs elsewhere now, it might be a different issue. If that's the case remove your post please and create a new issue.
If this is only a JIT issue it's important to know that - does it also have problems without JIT?

**Comment by amirlou** [comment]
no it doesn't have texture problem without jit but if jit is enable game get texture problem with snow but game still freeze after first time sleeping i open a new issue with log

**Comment by JohnGodgames** [comment]
Already fixed in recent master
